---

- name: playbook to install and configure httpd
  hosts: webservers
  become: yes
  
  vars: 
    ansible_become_pass: "vagrant"

  tasks:

  - name: install httpd
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: copy the index file
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: start httpd service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes


...
